//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission5Lib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int Id { get; set; }
        public int LateFeePerDay { get; set; }
        public int NumOfBooksCanCheckOut { get; set; }
        public int RentDays { get; set; }
    }
}
